version: "3.9"

services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      CLOUDINARY_API_KEY: 126232486978541
      CLOUDINARY_API_SECRET: aByXkqcXI9y4fAVs7OBzPqGSVsY
      CLOUDINARY_CLOUD_NAME: ovdrfpf7
      FRONTEND_URL: https://indore-corporation-area-athletics-as.netlify.app
      MONGODB_URI: ${MONGODB_URI}
      NODE_TYPE: DEVELOPMENT
      PORT: 8000
      SALT_ROUND: 10
      JWT_SECRET_KEY: supersecretjwtkey12345
      JWT_EXPIRE_IN: 7d
      EMAIL_USER: arpitcloud11@gmail.com
      EMAIL_PASS: qopmrateglnjyalt
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: [ "node", "src/workers/email.worker.js" ]
    environment:
      NODE_ENV: production
      MONGODB_URI: ${MONGODB_URI}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - redis

volumes:
  mongo-data:
